### ISSUE TITLE
项目运行起来如何访问

### ISSUE THREAD

**Issue by JasonY97** [yeqifu/carRental#5]
tomcat已经运行起来，并且没有报错，为什么访问不了localhost:8080,更别说访问项目了。。。求大佬知道，感谢

**Comment by yeqifu** [comment]
你描述的不够详细，加我QQ：1784525940  我给你看一下把。记得备注自己的名字

**Comment by JasonY97** [comment]
感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yeqifu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月24日(星期天) 晚上7:49
收件人:&nbsp;"yeqifu/carRental"<carRental@noreply.github.com&gt;;
抄送:&nbsp;"1281028036"<1281028036@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yeqifu/carRental] 项目运行起来如何访问 (#5)




你描述的不够详细，加我QQ：1784525940  我给你看一下把。记得备注自己的名字

**Comment by billc114** [comment]
你好，求指导怎么运行。。我也运行不起来，找不到主类

**Comment by billc114** [comment]
方便加个qq吗1137099334

**Comment by JasonY97** [comment]
前提是你所有的环境都配好了&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"billc114"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月26日(星期二) 晚上7:28
收件人:&nbsp;"yeqifu/carRental"<carRental@noreply.github.com&gt;;
抄送:&nbsp;"1281028036"<1281028036@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yeqifu/carRental] 项目运行起来如何访问 (#5)




方便加个qq吗1137099334

**Comment by JasonY97** [comment]
tomcat运行后访问网址是：localhost:8080/carRental
账号&nbsp; admin
密码 123456




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"billc114"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月26日(星期二) 晚上7:28
收件人:&nbsp;"yeqifu/carRental"<carRental@noreply.github.com&gt;;
抄送:&nbsp;"1281028036"<1281028036@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yeqifu/carRental] 项目运行起来如何访问 (#5)




你好，求指导怎么运行。。我也运行不起来，找不到主类

**Comment by YaleXin** [comment]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'deskManager' defined in file [C:\Users\YaleXin\IdeaProjects\carRental\target\carRental\WEB-INF\classes\com\yeqifu\sys\controller\DeskManager.class]: Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.aspectj.util.LangUtil
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:591)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
		at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
		at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
		at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:758)
		at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
		at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
		at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:409)
		at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:291)
		at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4689)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5155)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1719)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:564)
		at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:286)
		at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:809)
		at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
		at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:479)
		at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:428)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:564)
		at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:286)
		at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:809)
		at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
		at java.management/com.sun.jmx.remote.security.MBeanServerAccessController.invoke(MBeanServerAccessController.java:468)
		at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1466)
		at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307)
		at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
		at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1406)
		at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:827)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:564)
		at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
		at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
		at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
		at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
		at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
		at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
		at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
		at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
		at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
		at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
		at java.base/java.lang.Thread.run(Thread.java:832)
	Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.aspectj.util.LangUtil
		at org.aspectj.weaver.reflect.ReflectionWorld.<init>(ReflectionWorld.java:52)
		at org.aspectj.weaver.tools.PointcutParser.setClassLoader(PointcutParser.java:221)
		at org.aspectj.weaver.tools.PointcutParser.<init>(PointcutParser.java:207)
		at org.aspectj.weaver.tools.PointcutParser.getPointcutParserSupportingSpecifiedPrimitivesAndUsingSpecifiedClassLoaderForResolution(PointcutParser.java:168)
		at org.springframework.aop.aspectj.AspectJExpressionPointcut.initializePointcutParser(AspectJExpressionPointcut.java:241)
		at org.springframework.aop.aspectj.AspectJExpressionPointcut.buildPointcutExpression(AspectJExpressionPointcut.java:220)
		at org.springframework.aop.aspectj.AspectJExpressionPointcut.obtainPointcutExpression(AspectJExpressionPointcut.java:197)
		at org.springframework.aop.aspectj.AspectJExpressionPointcut.getClassFilter(AspectJExpressionPointcut.java:176)
		at org.springframework.aop.support.AopUtils.canApply(AopUtils.java:224)
		at org.springframework.aop.support.AopUtils.canApply(AopUtils.java:283)
		at org.springframework.aop.support.AopUtils.findAdvisorsThatCanApply(AopUtils.java:315)
		at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findAdvisorsThatCanApply(AbstractAdvisorAutoProxyCreator.java:124)
		at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findEligibleAdvisors(AbstractAdvisorAutoProxyCreator.java:93)
		at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.getAdvicesAndAdvisorsForBean(AbstractAdvisorAutoProxyCreator.java:74)
		at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:352)
		at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:304)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:438)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1714)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:583)
		... 57 more


你好，请问这个是如何解决的呢
